/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataKaryawan.java
 *
 * Created on Apr 24, 2012, 4:57:42 AM
 */
package Data;
import java.sql.*;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author izani
 */
public class DataKaryawan extends javax.swing.JFrame {
    
    /** Creates new form DataKaryawan */
    public DataKaryawan() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_nokar = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_gapok = new javax.swing.JLabel();
        lbl_jumlahjam = new javax.swing.JLabel();
        lbl_hargajam = new javax.swing.JLabel();
        lbl_bonus = new javax.swing.JLabel();
        txt_nokar = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_gapok = new javax.swing.JTextField();
        txt_jumlahjam = new javax.swing.JTextField();
        txt_hargajam = new javax.swing.JTextField();
        txt_bonus = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_totalgaji = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gaji Lembur Karyawan");

        lbl_nokar.setText("No Karyawan");

        lbl_nama.setText("Nama");

        lbl_gapok.setText("Gapok");

        lbl_jumlahjam.setText("Jumlah Jam Kerja");

        lbl_hargajam.setText("Harga / Jam");

        lbl_bonus.setText("Bonus");

        txt_nokar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nokarKeyReleased(evt);
            }
        });

        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_namaKeyReleased(evt);
            }
        });

        txt_gapok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_gapokKeyReleased(evt);
            }
        });

        txt_hargajam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hargajamKeyReleased(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Gaji");

        jLabel3.setText("Rp");

        jLabel4.setText("Rp");

        jLabel5.setText("Rp");

        jLabel6.setText("Rp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nama)
                            .addComponent(lbl_nokar)
                            .addComponent(lbl_jumlahjam)
                            .addComponent(lbl_bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_hargajam, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_gapok, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btn_cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_keluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_totalgaji)
                            .addComponent(txt_nama)
                            .addComponent(txt_bonus)
                            .addComponent(txt_hargajam)
                            .addComponent(txt_jumlahjam)
                            .addComponent(txt_nokar, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txt_gapok))))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nokar)
                    .addComponent(txt_nokar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nama)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gapok)
                    .addComponent(txt_gapok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jumlahjam)
                    .addComponent(txt_jumlahjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hargajam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_hargajam)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bonus)
                    .addComponent(txt_bonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_totalgaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_ubah)
                    .addComponent(btn_hapus)
                    .addComponent(btn_cari)
                    .addComponent(btn_reset)
                    .addComponent(btn_keluar))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
// TODO add your handling code here:
    try {
        
        Koneksi objkoneksi = new Koneksi ();
        Connection con = Koneksi.bukakoneksi();
        Statement stat = con.createStatement();
        String sql = "insert into \"data_gaji_karyawan\" values " 
                + "('" + txt_nokar.getText()+ "','" + txt_nama.getText()+ "','" + txt_gapok.getText()+ "','" + 
                txt_jumlahjam.getText()+ "','" + txt_hargajam.getText() + "','"  + txt_bonus.getText()+ "','" +
                txt_totalgaji.getText() + "')"; 
        int rows = stat.executeUpdate(sql);
        JOptionPane.showMessageDialog(this, "Data telah tersimpan!", "Message", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException se) {
     System.err.println(se);
    } catch (Exception e) {
     System.err.println(e);   
    }
    btn_ubah.setEnabled(false);
   btn_hapus.setEnabled(true);
   btn_simpan.setEnabled(false);
}//GEN-LAST:event_btn_simpanActionPerformed

private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
// TODO add your handling code here:
    try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con = Koneksi.bukakoneksi();
            Statement stat = con.createStatement();
            String sql = "update \"data_gaji_karyawan\" set \"Nama\"    = '" + txt_nama.getText() + "'," +
                   "\"Gapok\"        = '" + txt_gapok.getText() + "'," +
                    "\"Jumlah_Jam\"    = '" + txt_jumlahjam.getText() + "'," +
                    "\"Harga_Jam\"      = '" + txt_hargajam.getText() + "'," +
                    "\"Bonus\"    =  '" + txt_bonus.getText() + "'," +
                    "\"Total_Gaji\"   = '" + txt_totalgaji.getText() + "' " +
                    "where \"No_Kar\"     = '" + txt_nokar.getText() + "'";

            int rows = stat.executeUpdate(sql);

            if (rows == 1) {
                JOptionPane.showMessageDialog(this, "Perubahan berhasil!", "Message", JOptionPane.INFORMATION_MESSAGE);
            }
              else {
                JOptionPane.showMessageDialog(this, "Perubahan Gagal!", "Message", JOptionPane.INFORMATION_MESSAGE);
              }

        }
        catch(SQLException e) {

        }
}//GEN-LAST:event_btn_ubahActionPerformed

private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
// TODO add your handling code here:
   try {
            Koneksi objkoneksi = new Koneksi();
            Connection con = Koneksi.bukakoneksi();
            Statement stat = con.createStatement();
            String sql = "Delete from \"data_gaji_karyawan\" where \"No_Kar\" = '" + txt_nokar.getText() + "'";
            stat.executeUpdate(sql);
            
            txt_nokar.setText("");
            txt_nama.setText("");
            txt_gapok.setText("");
            txt_jumlahjam.setText("");
            txt_hargajam.setText("");
            txt_bonus.setText("");
            txt_totalgaji.setText("");
                    
            btn_simpan.setEnabled(true);           
            JOptionPane.showMessageDialog(this, "Data telah dihapus!", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e) {
        }
}//GEN-LAST:event_btn_hapusActionPerformed

private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
// TODO add your handling code here:
    try {
            Koneksi objkoneksi = new Koneksi();
            Connection con = Koneksi.bukakoneksi();
            Statement stat = con.createStatement();
            String sql = "select * from \"data_gaji_karyawan\" where  \"No_Kar\" = '" + txt_nokar.getText() + "'";

            ResultSet rs = stat.executeQuery(sql);

            if (rs.next()) {
                   txt_nama.setText("" + rs.getString("Nama"));
                   txt_gapok.setText("" + rs.getString("Gapok"));
                   txt_jumlahjam.setText("" + rs.getString("Jumlah_Jam"));
                   txt_hargajam.setText("" + rs.getString("Harga_Jam"));
                   txt_bonus.setText("" + rs.getString("Bonus"));
                   txt_totalgaji.setText("" + rs.getString("Total_Gaji"));      

                   btn_simpan.setEnabled(false);
                   btn_ubah.setEnabled(true);
                   btn_hapus.setEnabled(true);
                   txt_nokar.requestFocus();

             }
            else {
                btn_simpan.setEnabled(true);
                btn_ubah.setEnabled(false);
                btn_hapus.setEnabled(false);
                txt_nokar.requestFocus();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!", "Message", JOptionPane.INFORMATION_MESSAGE);
            }

        }

        catch(SQLException e ) {

        }

}//GEN-LAST:event_btn_cariActionPerformed

private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
// TODO add your handling code here:
        txt_nokar.setText("");
        txt_nama.setText("");
        txt_gapok.setText("");
        txt_jumlahjam.setText("");
        txt_hargajam.setText("");
        txt_bonus.setText("");
        txt_totalgaji.setText("");
        btn_simpan.setEnabled(true);  
        btn_ubah.setEnabled(false);
   btn_hapus.setEnabled(false);
}//GEN-LAST:event_btn_resetActionPerformed

private void txt_hargajamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargajamKeyReleased
// TODO add your handling code here:
      {
             int jum_jam = Integer.parseInt(txt_jumlahjam.getText());
             int gapok = Integer.parseInt(txt_gapok.getText());
          double bonus = 0;
               
      if ( jum_jam >=40 && jum_jam <=50) {
          bonus = 250000;
      }
      else if (jum_jam >50 && jum_jam <=100){
          bonus = gapok;
      }
      
      String output = String.valueOf(bonus);
      txt_bonus.setText(output);
}
      {
        
        
       double total_gaji = 0;
       double gapok = Double.parseDouble(txt_gapok.getText());
       double jum_jam = Double.parseDouble(txt_jumlahjam.getText());
       double persen = 0;
       double bonus = Double.parseDouble(txt_bonus.getText());
       double harga_jam = Double.parseDouble(txt_hargajam.getText());
       
        
        if ( jum_jam >= 10 && jum_jam >=25) {
            persen = 0.02;
        }
        else if ( jum_jam >=26 && jum_jam >= 40){
            persen = 0.05;
        }
        else if ( jum_jam >=41 && jum_jam >= 50){
            persen = 0.075;
        }
        
       
        
        total_gaji = (( gapok * persen ) + ( jum_jam * harga_jam )+ bonus);
       
       
        String output = String.valueOf(total_gaji);
        txt_totalgaji.setText(output);
        }
      
      btn_ubah.setEnabled(false);
   btn_hapus.setEnabled(false);
}//GEN-LAST:event_txt_hargajamKeyReleased

private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_btn_keluarActionPerformed

private void txt_nokarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nokarKeyReleased
// TODO add your handling code here:
       btn_ubah.setEnabled(false);
       btn_hapus.setEnabled(false);
}//GEN-LAST:event_txt_nokarKeyReleased

private void txt_namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyReleased
// TODO add your handling code here:
   btn_ubah.setEnabled(false);
   btn_hapus.setEnabled(false);
}//GEN-LAST:event_txt_namaKeyReleased

private void txt_gapokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_gapokKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txt_gapokKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DataKaryawan().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_bonus;
    private javax.swing.JLabel lbl_gapok;
    private javax.swing.JLabel lbl_hargajam;
    private javax.swing.JLabel lbl_jumlahjam;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nokar;
    private javax.swing.JTextField txt_bonus;
    private javax.swing.JTextField txt_gapok;
    private javax.swing.JTextField txt_hargajam;
    private javax.swing.JTextField txt_jumlahjam;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nokar;
    private javax.swing.JTextField txt_totalgaji;
    // End of variables declaration//GEN-END:variables
}
